import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import spacesRouter from "./spaces";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import adminRouter from "./admin";
import smartprisRouter from "./smartpris";
import availabilityRouter from "./availability";
import subscriptionsRouter from "./subscriptions";
import waitlistRouter from "./waitlist";
import vippsRouter from "./vipps";
import unlocRouter from "./unloc";
import telemetricsRouter from "./telemetrics";
import reiseRouter from "./reise";
import alarmerRouter from "./alarmer";
import borettslagRouter from "./borettslag";
import gavekortRouter from "./gavekort";
import bytteRouter from "./bytte";
import widgetRouter from "./widget";
import kalenderRouter from "./kalender";
import arrangementerRouter from "./arrangementer";
import meglerRouter from "./megler";
import pendlerRouter from "./pendler";
import aiChatRouter from "./ai-chat";
import lanseringslisteRouter from "./lanseringsliste";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(spacesRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(adminRouter);
router.use(smartprisRouter);
router.use(availabilityRouter);
router.use(subscriptionsRouter);
router.use(waitlistRouter);
router.use(vippsRouter);
router.use(unlocRouter);
router.use(telemetricsRouter);
router.use(reiseRouter);
router.use(alarmerRouter);
router.use(borettslagRouter);
router.use(gavekortRouter);
router.use(bytteRouter);
router.use(widgetRouter);
router.use(kalenderRouter);
router.use(arrangementerRouter);
router.use(meglerRouter);
router.use(pendlerRouter);
router.use(aiChatRouter);
router.use(lanseringslisteRouter);

export default router;
